/* Palette generated by Material Palette - materialpalette.com/teal/deep-orange */
export default {
	primaryColorDark: '#E64A19',
	primaryColor: '#FF5722',
	primaryColorLight: '#FFCCBC',
	primaryColorText: '#FFFFFF',
	accentColor: '#607D8B',
	primaryTextColor: '#212121',
	secondaryTextColor: '#757575',
	dividerColor: '#BDBDBD',
  headerHeight: '10vh',
	footerHeight: '30vh'
}
